### ISSUE TITLE
Tag Naming Pattern

### ISSUE THREAD

**Issue by CRCError1970** [audiamus/AaxAudioConverter#5] opened 2019-07-29 05:17 UTC
When making a single MP3 from an AAX file, I'd like to be able to remove the "<track> - " from the "File naming pattern" and the "Title tag naming pattern"

If there's only one track, having the track number is redundant and it would make importing my audio files into PLEX cleaner.

**Comment by audiamus** [comment] 2019-07-30 17:58
Just tried it myself. 

For the file naming pattern, no track number was generated for a single mp3 or m4a file, largely independent of the setting. It will show for a multi-part book, though.

For the title tag naming pattern, when selecting a pattern without track, no track number was generated.  

Which settings did you use?

**Comment by audiamus** [comment] 2019-08-25 16:49
As I could not reproduce this I close this for the time being.

**Closed by audiamus** 2019-08-25 16:49 UTC
Labels: enhancement, question
