### ISSUE TITLE
Conversion Hangs Creating Multiple Files

### ISSUE THREAD

**Issue by Phiber2000** [audiamus/AaxAudioConverter#194] opened 2023-10-16 10:51 UTC
I have the same problem here but it seems to be a different issue than #186.

The conversion stops after some files and then stops responding.
Changing the configuration parameters or replacing the `ffmpeg.exe` does not solve the issue.

Loglevel 4 logfile:
[AaxAudioConverter_2023-10-16_001.log](https://github.com/audiamus/AaxAudioConverter/files/12915376/AaxAudioConverter_2023-10-16_001.log)

**Comment by audiamus** [comment] 2023-10-16 13:13
From the log file it seems that writing meta data to chapter 6 hangs, presumably when invoking ATL. 

Does it also hang if
- in split chapter mode (5 min per track)?
- converting to m4b/m4a?

_The "NonParallel" app setting is really helpful hear to decipher the log file. Please leave it on for these tests._

**Comment by Phiber2000** [comment] 2023-10-16 14:59
- Format "M4A", Mode "One file"
**success**
- Format "M4A", Mode "Multiple files, by chapter, split into shorter tracks, 5m"
**fail**
- Format "M4A", Mode "Multiple file, ignoring chapters, split into shorter tracks, 5m"
**fail** (logfile attached)
- Format "MP3", Mode "One file"
**success**
- Format "MP3", Mode "Multiple files, by chapter, split into shorter tracks, 5m"
**fail**
- Format "MP3", Mode "Multiple file, ignoring chapters, split into shorter tracks, 5m"
**fail**

[AaxAudioConverter_2023-10-16_002.log](https://github.com/audiamus/AaxAudioConverter/files/12918370/AaxAudioConverter_2023-10-16_002.log)

**Comment by audiamus** [comment] 2023-10-16 17:11
Strange. I don't see any regularities here yet.

**Comment by Phiber2000** [comment] 2023-10-16 17:27
I only see as common factor, that the program freezes in all cases after transcoding the 6th track.

**Comment by Phiber2000** [comment] 2023-10-16 18:01
No issues with v1.17.1. I'm checking the versions between...

**Comment by Phiber2000** [comment] 2023-10-16 18:08
The issue introduced with v1.18.0. It's reproducible and not related to the input AAX file.

**Comment by audiamus** [comment] 2023-10-16 18:49
> The issue introduced with v1.18.0. 

That's helpful. I'll check what changes were made. If it is related to ATL I could revert to an older (or newer) version there. I might build an intermediate version of AaxAudioConverter for you to test. But it will have to wait a few days, this week is going to be rather busy for me.

**Comment by audiamus** [comment] 2023-10-22 10:09
Here are two test builds to find out whether the issue is likely to be caused by ATL. 

- 1.18.2.1 is linked to ATL 3.20, as it was with AAXAudioConverter 1.17.1. 
- 1.18.2.2 is linked to ATL 4.36, the latest that supports .Net Framework.
- No other changes.

[AaxAudioConverter_1.18.2.n.zip](https://github.com/audiamus/AaxAudioConverter/files/13062885/AaxAudioConverter_1.18.2.n.zip)

Unpack to `C:\Program Files\audiamus\AAX Audio Converter`, where all other resources of this app reside.

**Comment by FooDeas** [comment] 2023-10-22 17:14
No changes with both ATL variants. 😢

**Comment by Phiber2000** [comment] 2023-10-22 17:16
No changes with both ATL variants. 😢

**Comment by audiamus** [comment] 2023-10-22 18:27
Can you contact me on Reddit? My user name there is also audiamus.

**Comment by audiamus** [comment] 2023-11-09 12:03
As discussed on Reddit, here is the next attempt. 

[AaxAudioConverter_1.18.2.3.zip](https://github.com/audiamus/AaxAudioConverter/files/13307773/AaxAudioConverter_1.18.2.3.zip)

In the `AaxAudioConverter_1.18.2.3.exe.config` file there is a new setting in the `applicationSettings` group, named `MaxParallelThreads`. You can play around with that and, for instance, use 4 initially. `NonParallel` will override it and it can't be higher than the number of CPU cores. The setting will be shown in the log file.

**Comment by Phiber2000** [comment] 2023-11-13 15:17
In fact, still without success. 😢 
I tried `MaxParallelThreads=4` and `MaxParallelThreads=NonParallel` (log attached).

[AaxAudioConverter_2023-11-13_001.log](https://github.com/audiamus/AaxAudioConverter/files/13336161/AaxAudioConverter_2023-11-13_001.log)

**Comment by audiamus** [comment] 2023-11-13 17:04
This log file says, `NonParallel = True` and `MaxParallelThreads = 0`. NonParallel overrides MaxParallelThreads which means all parallel loops run single-threaded.  MaxParallelThreads with default 0 means no restriction but does not come into effect here, because of NonParallel.

So, not really anything new here, unfortunately.

**Comment by Phiber2000** [comment] 2023-11-14 00:43
Sorry, I misunderstood that! Here you go: [AaxAudioConverter_2023-11-14_001.log](https://github.com/audiamus/AaxAudioConverter/files/13343266/AaxAudioConverter_2023-11-14_001.log)

**Comment by audiamus** [comment] 2023-11-14 08:27
Same as before, I'm afraid. But that was to be expected.

What we know so far: 

- It seems to be dependent on one particular book.
- It seems to be dependent on one particular machine.
- As soon as this book is converted in any of the split modes, the converter hangs, reproducibly, and at the same spot.
- The issue seems to appear somewhere around the end of an FFmpeg sub-process and writing meta data with ATL.
- It seems to be independent of parallelization.

**Comment by audiamus** [comment] 2023-11-29 08:56
I close this for now. As said before, as I am not able to reproduce this with my books and my environment.

**Closed by audiamus** 2023-11-29 08:56 UTC
