### ISSUE TITLE
Big files display a duration of 00:00:00

### ISSUE THREAD

**Issue by ikarusnc** [audiamus/AaxAudioConverter#9] opened 2019-12-26 14:37 UTC
I have two big Audiobooks, one is 951MB the other one is 1149MB, both display 00:00:00 duration. Thank you for this software, is probably the best free aax converter!

**Comment by audiamus** [comment] 2020-01-08 18:43
As said in the comment to #10 I haven't tested large files. I am always using the Audible option to download the book in parts and then recombine into one playlist with AAX Audio Converter.
 
What might happen with very long books - but this is pure speculation - is that we run into limitations of the FFmpeg plug-in for monitoring time.

**Comment by audiamus** [comment] 2020-01-11 11:21
I've found the cause of the problem: incompatibility between the format in which FFmpeg presents the duration and the format that the .Net TimeSpan type expects. It will be fixed in the next version, I will apply some custom parsing here.

It only affects aax files longer than 24 hours. FFmpeg just increases the number of hours when longer than one day while TimeSpan only accepts a maximum of 23:59:59 and beyond that expects explicit number of days.

As a work-around for the time being, use the Audible option to download such long books in multiple smaller parts.

**Comment by audiamus** [comment] 2020-02-08 11:31
Fixed in version 1.7.

**Closed by audiamus** 2020-02-08 11:31 UTC
Labels: bug
