### ISSUE TITLE
Book title trimmed when there's a symbol in it.

### ISSUE THREAD

**Issue by Squaredude** [audiamus/AaxAudioConverter#16] opened 2020-03-08 23:58 UTC
Version: 1.8
Net Framework: 4.8.3752
Windows 10 64bits

In order to avoid a messy conversation, I created this separate issue.

This one is far less serious, as the audiobook is converted without exceptions thrown or anything missing.

However, when the title has an "&", the title is trimmed.

Example:

Original title: Fire & Blood

Outputs: Fire

Fire is used in the book's folder, chapter/track names ("Chapter # - Fire.xyz"), and "Fire" in each track's album tag.

**Comment by audiamus** [comment] 2020-03-09 10:18
> Original title: Fire & Blood, Outputs: Fire

This is by design but harmless enough.

AAX Audio Converter analyses the given text string for the book title to identify 
- the title proper, 
- any mulit-part info, 
- a possible series title 
- and "noise" that should be discarded.

Unless defined as valid, any punctuation mark in the string will terminate the book title. (There is a short predefined list of characters, like comma and dot, that will always be accepted.) 

Often this works, but it sometimes may go wrong as it does in your example. To overcome this, you have two options:
- Either explicitly set the book title in the Preview/customization window. Will apply only to the current book (all parts) and the current session.  
- Or add the punctuation mark in question, the ampersand in your case, in the Basic Settings, field "Additional valid punctuation". Will apply to all books and all sessions until changed again.

**Comment by Squaredude** [comment] 2020-03-09 22:02
I didn't realize there were such additional options. (Yeah, I should have tried reading the help file. :P)

However, following your second suggestion, I ran into a problem:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.ArgumentException: parsing "^([\w+\s+\.,'/-&]+)\W*" - [x-y] range in reverse order.
>    at System.Text.RegularExpressions.RegexParser.ScanCharClass(Boolean caseInsensitive, Boolean scanOnly)
>    at System.Text.RegularExpressions.RegexParser.ScanRegex()
>    at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
>    at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
>    at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
>    at audiamus.aaxconv.lib.Book.initRegexTitle(ITitleSettingsEx settings)
>    at audiamus.aaxconv.lib.Book.InitAuthorTitle(ITitleSettingsEx settings)
>    at audiamus.aaxconv.lib.AaxAudioConverter.TitlePreview(AaxFileItem fileItem)
>    at audiamus.aaxconv.PreviewForm.setTitle(Boolean update)
>    at audiamus.aaxconv.PreviewForm.updatePreview(Boolean update)
>    at audiamus.aaxconv.PreviewForm.Set(AaxFileItem fileItem)
>    at audiamus.aaxconv.MainForm.openNonModalForm[F](AaxFileItem fi, F& form, FormClosedEventHandler handler)
>    at audiamus.aaxconv.MainForm.openPreviewForm(AaxFileItem fi)
>    at audiamus.aaxconv.MainForm.tsmiPreview_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Following the first suggestion worked fine, though.

**Comment by audiamus** [comment] 2020-03-10 18:11
That's tricky. I added the hyphen as a valid title character in version 1.8. Theoretically, the hyphen is treated as a literal character in Regular Expressions (regex). Unless it is used in a regex token. And unfortunately, that can be the case here. So when you add the ampersand, the hyphen changes its meaning now indicating a range.  

But when you "escape" the ampersand, the hyphen can fulfil its range role. The actual regex pattern becomes `^([\w+\s+\.,'/-\\&]+)\W*`, as the backslash is higher in order than the forward slash. The hyphen, however, gets lost. The correct regex pattern should look like this: `^([\w+\s+\.,'/\-]+)\W*` and then you can add the ampersand without problems: `^([\w+\s+\.,'/\-&]+)\W*`.

**Comment by Squaredude** [comment] 2020-03-10 22:53
That's awesome. Regex is awesome, but such an annoyance to debug. :P

**Comment by audiamus** [comment] 2020-03-28 13:12
Fixed in version 1.9.

**Closed by audiamus** 2020-03-28 13:12 UTC
Labels: bug, question
